# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
